### Numpy

In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [6]:
print(a.dtype)

int64


In [9]:
a=np.array(['abc','def','puy'])

In [11]:
print(a.dtype)

<U3


In [12]:
br=np.arange(1,11,4)

In [13]:
br

array([1, 5, 9])

In [14]:
br.dtype

dtype('int64')

In [15]:
lr=np.linspace(1,5,2)

In [16]:
lr

array([1., 5.])

In [17]:
lr.dtype

dtype('float64')

In [18]:
nz=np.zeros(5,5)

TypeError: Cannot interpret '5' as a data type

In [19]:
nz=np.zeros((5,5))

In [20]:
nz

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
nz.dtype

dtype('float64')

In [22]:
nz=np.zeros((5,5,5))

In [23]:
nz

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [24]:
nz.ndim

3

In [25]:
nz.shape

(5, 5, 5)

In [26]:
## np.ones

In [29]:
npo=np.ones((4,4))

In [30]:
npo


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
npo.shape

(4, 4)

In [32]:
npo.dtype

dtype('float64')

In [33]:
npo=np.ones((4,4),dtype=np.int8)

In [34]:
npo

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [35]:
npo.dtype

dtype('int8')

In [36]:
npo.ndim

2

In [37]:
npo.shape

(4, 4)

In [38]:
npf=np.full(7,10)

In [39]:
npf

array([10, 10, 10, 10, 10, 10, 10])

In [40]:
npf.shape

(7,)

In [41]:
npf.ndim

1

In [42]:
npf.dtype

dtype('int64')

In [43]:
npf=np.full((7,8),10)

In [44]:
npf

array([[10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10]])

In [45]:
npf.ndim

2

In [46]:
npf.dtype

dtype('int64')

In [47]:
npf.shape

(7, 8)

### identity Matrix

In [48]:
a=np.eye(3)

In [49]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
a=np.eye(6)

In [51]:
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [52]:
a=np.eye(7)

In [53]:
a

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [54]:
np.eye(7,9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.]])

In [ ]:
a=np.eye(7,6,3) # changed diagnol to 3rd index

In [56]:
a

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.empty((3,3),dtype='int8') #random garbage value

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [ ]:
np.empty((3,3),dtype='int8') #random garbage value

array([[ 80, 121,  53],
       [ 22,  -6, 127],
       [  0,   0,   0]], dtype=int8)

In [62]:
np.empty((3,3),dtype='int8') #random garbage value

array([[ 16,  23, 110],
       [-13, -10,   1],
       [  0,   0,  32]], dtype=int8)

In [63]:
np.random.rand(2,4)

array([[0.34774826, 0.53789899, 0.25885009, 0.58559727],
       [0.01420418, 0.08337527, 0.7191085 , 0.27921882]])

In [64]:
np.random.rand(3,5)

array([[9.46476103e-01, 2.97453614e-01, 6.35047080e-04, 4.66143346e-01,
        7.13873346e-02],
       [4.28833891e-01, 3.54191734e-01, 4.47437605e-01, 7.58997446e-01,
        1.83679441e-01],
       [5.50031730e-01, 6.12228116e-01, 2.06996131e-01, 1.93699083e-01,
        5.74348030e-01]])

In [67]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [70]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [71]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [75]:
np.random.rand(2,2)

array([[0.2105145 , 0.17877784],
       [0.13650838, 0.98427689]])

In [76]:
a

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [81]:
a.reshape(6,7)

array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [83]:
a

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [84]:
a.T

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.]])

In [86]:
a=np.arange(1,11,1)

In [87]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
a[2]

np.int64(3)

In [89]:
print(a[2])

3


In [90]:
a[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
a[::2]

array([1, 3, 5, 7, 9])

In [95]:
b=np.arange(1,11)

In [98]:
b=b.reshape(5,2)

In [99]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [105]:
print(b[2][1])

6


In [106]:
print(b[1,1])

4


In [107]:
print(b[:,1])

[ 2  4  6  8 10]


In [108]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [110]:
print(b[1:4,:])

[[3 4]
 [5 6]
 [7 8]]


In [111]:
b>5

array([[False, False],
       [False, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

In [112]:
print(b[b>5])

[ 6  7  8  9 10]


In [113]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [116]:
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [118]:
print(np.sum(b))

55


In [119]:
print(np.mean(b))

5.5


In [120]:
print(np.std(b))

2.8722813232690143


In [121]:
print(np.max(b))

10


In [122]:
print(np.min(b))

1
