## Faster , Optimised, Mathematical, written in C 

# Numpy

In [1]:
import numpy as np
import time

In [2]:
# Array is a datatype that is present in C, C#, Java but we dont have it directly in python,so, we have numpy

In [3]:
# Arrays : Always have same data type. it is called as np.array

### NumpyArray - np.array()

In [4]:
array_n1=np.array([1,2,3])

In [5]:
array_n1

array([1, 2, 3])

In [6]:
type(array_n1)

numpy.ndarray

In [7]:
print(array_n1.dtype)


int64


## np.arange(5)

In [8]:
a=np.arange(1,5)

In [9]:
a

array([1, 2, 3, 4])

In [10]:
a=np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [11]:
print(a.dtype)

int64


## linspace(start,stop, how many equal intervals)

In [12]:
a=np.linspace(0,1,10)
a


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
print(a.dtype)

float64


In [14]:
a=np.linspace(0,1,4)
a


array([0.        , 0.33333333, 0.66666667, 1.        ])

## np.zeros(shape)

In [15]:
a=np.zeros(5)

In [16]:

a

array([0., 0., 0., 0., 0.])

In [17]:
a=np.zeros((5,5))

In [18]:
a.ndim

2

In [19]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
a=np.zeros((5,5,5))

In [21]:
a

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [22]:
a.ndim

3